version: '3'
services:




  db_host:
   container_name: mysql
   image: mysql:5.7
   command:
     - --init-file /data/application/init.sql
   environment:
     - "MYSQL_ROOT_PASSWORD=1234"
   volumes:
     - "/db_data:/var/lib/mysql"
     - ./init.sql:/data/application/init.sql
   networks:
     - net


  web-app:
    container_name: web-app
    image: "books-manager:$BUILD_TAG"
    build:
      context: .
    ports:
      - "8081:8081"
    depends_on:
      - db_host
    networks:
      - net

networks:
  net: