version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - /db_data:/var/lib/mysql

    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=books_store
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=1234
    networks:
      - net
#
#  mysql:
#   container_name: mysql
#   image: mysql:5.7
#
#   environment:
#     - "MYSQL_ROOT_PASSWORD: 1234"
#     - "MYSQL_DATABASE: books_store"
#
#   volumes:
#     - /db_data:/var/lib/mysql
#   networks:
#     - net


#  web-app:
#    container_name: web-app
#    image: "books-manager:$BUILD_TAG"
#    build:
#      context: .
#    environment:
#      - "DATABASE_HOST=jdbc:mysql://mysql:3306/books-store"
#      - "DATABASE_USERNAME=root"
#      - "DATABASE_PASSWORD=1234"
#      - "SERVER_PORT=8081"
#    ports:
#      - "8081:8081"
#    depends_on:
#      - mysql
#    networks:
#      - net

networks:
  net: