server:
  port: 8080


spring:
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none


  datasource:
    url: ${DATABASE_HOST:jdbc:mysql://localhost:3306/books_store}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:localhost}



